### ISSUE TITLE
Bug in non-userspace-networking

### ISSUE THREAD

**Issue by yudshj** [anasfanani/Magisk-Tailscaled#13]
I tried removing the startup parameter `-tun=userspace-networking`. After restarting the device, I am unable to log in to Tailscale.

When I use `tailscale netcheck`, I receive the following [error message](https://github.com/linuxscreen/TailscaleForMagisk/issues/1):

```
1|:/data/data/com.termux/files/home # tailscale netcheck
2024/01/28 05:08:40 No DERP map from tailscaled; using default.
fetch prodDERPMap failed: Get "https://controlplane.tailscale.com/derpmap/default": dial tcp: lookup controlplane.tailscale.com on [::1]:53: read udp [::1]:50349->[::1]:53: read: connection refused
```

**Comment by anasfanani** [comment]
Yeah, for me its not works too. it must run on userspace networking mode only. 
This depends on tailscale binary, if you want to run in non userspace networking, please open issue in official tailscale repository.

**Comment by ri-char** [comment]
If there is another proxy application on your phone, you could connect to tailscale via it. Add these lines at the head of `start_tailscaled` function in `/data/adb/tailscale/scripts/tailscaled.service`

```
export HTTP_PROXY=http://127.0.0.1:7890/
export HTTPS_PROXY=http://127.0.0.1:7890/
```


But I don't know why `tailscaled` cannot connect to the Internet without a proxy. I tried to capture the packages using `tcpdump`, but found out nothing. Maybe some rules in iptables block it.

**Comment by anasfanani** [comment]
I'm sorry for verry late reply, I have other work :(
But just for inform you maybe still use tailscale module, check latest pre release at https://github.com/anasfanani/Magisk-Tailscaled/releases

You now can use direct connection to the tailscale IP

Let me close this issue, if you need help and discussion, come to telegram group brother.
I will do the best as I can for you.
