### ISSUE TITLE
Issue with rooted Android 14 LineageOS microG on Xperia 5 II

### ISSUE THREAD

**Issue by karol-terminalindex** [anasfanani/Magisk-Tailscaled#18]
> What is not working?
Pinging other Tailnet devices.

> Steps to reproduce:
Follow the guide to install the module and login to Tailscale.
then
Ping to any device in tailnet

> What's happening?
Every device can ping my phone, but phone cannot ping other tailnet devices.

**Comment by anasfanani** [comment]
try this

https://github.com/anasfanani/Magisk-Tailscaled/releases/tag/v1.64.0.0-socks5tun-dev

**Comment by anasfanani** [comment]
Already solved in latest version, thanks bro
