### ISSUE TITLE
Tailscaled.service does not Start on Boot when doing VOLUME UP (+) (Default) while installing

### ISSUE THREAD

**Issue by bioluks** [anasfanani/Magisk-Tailscaled#21]
Title.

No issues while and after the install - if you clicked the VOLUME DOWN (-) while installing. This way tailscaled.service will start after the booting process.

The default and encouraged option in the [installation wizard](https://github.com/anasfanani/Magisk-Tailscaled/blob/main/customize.sh#L59-L73) is the non-functional one. New users will probably click (+) and have tailscaled.service launch issues just like me. Sadly I have no proposed solution other than selecting (-) for now.

**Comment by anasfanani** [comment]
Thankyou for report, there already fixed in https://github.com/anasfanani/Magisk-Tailscaled/pull/20 , next release will fixed
