### ISSUE TITLE
It seems that private DERP will not be used.

### ISSUE THREAD

**Issue by momomobinx** [anasfanani/Magisk-Tailscaled#24]
![7afb04a13a4ae8288a4375d238e09fc](https://github.com/anasfanani/Magisk-Tailscaled/assets/21970770/db64a3cd-2297-4385-ae27-fc7188fefb20)

**Comment by momomobinx** [comment]
Is my dns configuration wrong

**Comment by anasfanani** [comment]
Let me develop android binary build, already done but still unstable for all user, you can check in other branch.
