### ISSUE TITLE
Feature Request: Trust user (self-signed) certificate.

### ISSUE THREAD

**Issue by APYYPZMF** [anasfanani/Magisk-Tailscaled#4]
Currently, the Android client does not trust self-signed certificates, not even ZeroSSL, and there are many issues with custom servers, see:

- https://github.com/tailscale/tailscale/issues/8085
- https://github.com/tailscale/tailscale/issues/10700

The official explanation is that trusting self-signed certificates poses security risks (https://github.com/tailscale/tailscale/issues/8085#issuecomment-1537430052).

However, on Linux and Windows, Tailscale works fine as long as you manually add self-signed certificates to the trusted list.

Can the same be done for this module? I think Magisk users can take responsibility for their own security.

**Comment by anasfanani** [comment]
> log:
> 
> ```
> 2023/12/30 00:15:29 control: doLogin(regen=true, hasUrl=false)
> 2023/12/30 00:15:29 tlsdial: error: server cert for "my-ip-addr" failed to verify and is not a Let's Encrypt cert
> 2023/12/30 00:15:29 Received error: fetch control key: Get "https://my-ip-addr:443/key?v=82": x509: certificate signed by unknown authority
> 2023/12/30 00:15:29 control: LoginInteractive -> regen=true
> ```

Did you solve the problem ? 

This is interesting, I even dont know what is Headscale for, can you give me other description ?

**Comment by anasfanani** [comment]
I test intall headscale, but ecounter configuration problem, also start and stop headscale service take 1 minutes 50 second.
I read a bit about trust anchor 

https://docs.samsungknox.com/dev/knox-sdk/features/mdm-providers/security/trust-anchors/

For trust android certificate, there a magisk module for that

https://github.com/NVISOsecurity/MagiskTrustUserCerts

**Comment by anasfanani** [comment]
> > I test intall headscale, but ecounter configuration problem, also start and stop headscale service take 1 minutes 50 second. I read a bit about trust anchor
> > https://docs.samsungknox.com/dev/knox-sdk/features/mdm-providers/security/trust-anchors/
> > For trust android certificate, there a magisk module for that
> > https://github.com/NVISOsecurity/MagiskTrustUserCerts
> 
> what is ecounter? start and stop Headscale should take effect immediately, maybe your config is wrong.
> 
> This Mgaisk module just changes user cert to system cert, but Tailscale android client doesn't trust either.

I'm sorry, typo at `encounter`.

> start and stop Headscale should take effect immediately, maybe your config is wrong.

Yes, my config is wrong, so i try config from example, adjust the config, then stop and start the daemon is verry long, 1 minute 30 second, make me give up to try.

```
ubuntu@ip-172-31-25-245:~$ sudo time systemctl stop headscale
0.00user 0.00system 1:30.10elapsed 0%CPU (0avgtext+0avgdata 6272maxresident)k
0inputs+0outputs (0major+603minor)pagefaults 0swaps
```

Can you share a working example config for headscale, so i can investigate the cert problem ?

> This Mgaisk module just changes user cert to system cert, but Tailscale android client doesn't trust either.

I use that module for trust client cert to android system, for Fiddler cert or other custom cert to install to system android.

I think it should be enough for trusting a certificate into system cert.
