### ISSUE TITLE
如何与box_for_magisk一起使用呢？

### ISSUE THREAD

**Issue by fgfg163** [anasfanani/Magisk-Tailscaled#6]
我想知道这个模块如何与box_for_magisk或者其他vpn软件一起使用

**Comment by anasfanani** [comment]
Hi, I mean it can be used with box_for_magisk because box_for_magisk itself is a VPN.

Can be run together with VPN.

**Comment by rexackermann** [comment]
Box for magisk for me works with it when mobile data is being used, but wifi... no luck so far.....
