### ISSUE TITLE
How to use subnet routes

### ISSUE THREAD

**Issue by powerAn2020** [anasfanani/Magisk-Tailscaled#8]
I configured the subnet on OpenWrt according to [this document](https://tailscale.com/kb/1019/subnets#step-6-use-your-subnet-routes-from-other-machines), but my phone cannot access the target network, although other devices can access it normally
[tailscaled.zip](https://github.com/anasfanani/Magisk-Tailscaled/files/13870607/tailscaled.zip)

**Comment by anasfanani** [comment]
Please check this issue, maybe because currently android tailscaled daemon wont connect to other tailscale network, but can accessed by other.

https://github.com/anasfanani/Magisk-Tailscaled/issues/5#issuecomment-1879841506

**Comment by anasfanani** [comment]
This should fix the existing problem, I've also added some shell scripts to control the daemon.
https://github.com/anasfanani/Magisk-Tailscaled/releases/tag/v1.56.1.3

I will close this issue, if you are still having problems, please reopen it. Thank you and don't forget to give ⭐ if this module is useful for you.
