### ISSUE TITLE
Unable to contact other connected devices

### ISSUE THREAD

**Issue by mhay10** [anasfanani/Magisk-Tailscaled#9]
I seem to be unable to ping other devices connected to Tailscale. The only way I can ping them is using `tailscale ping` which responds just fine. I can ping my phone from other devices but not vice versa. Is there a way to fix this or should I go back to using the Play Store app?

`tailscale ping` succeeds but `ping` does not:  
  
![image](https://github.com/anasfanani/Magisk-Tailscaled/assets/57298046/fdfea57a-b0dc-46ca-9674-b8c83a60bebe)

**Comment by anasfanani** [comment]
I prepare for new release to fix that, you can read this for now https://github.com/anasfanani/Magisk-Tailscaled/issues/5#issuecomment-1879841506

**Comment by anasfanani** [comment]
This should fix the existing problem, I've also added some shell scripts to control the daemon.
https://github.com/anasfanani/Magisk-Tailscaled/releases/tag/v1.56.1.3

I will close this issue, if you are still having problems, please reopen it. Thank you and don't forget to give ⭐ if this module is useful for you.

**Comment by bbbenji** [comment]
I seem to be having the same issue. I am on 1.58.2.0.

![Screenshot_20240210-223943](https://github.com/anasfanani/Magisk-Tailscaled/assets/1678118/66ba9ba4-a0c6-40a0-ae95-197e1824ae89)

**Comment by anasfanani** [comment]
> I seem to be having the same issue. I am on 1.58.2.0.
> 
> ![Screenshot_20240210-223943](https://github.com/anasfanani/Magisk-Tailscaled/assets/1678118/66ba9ba4-a0c6-40a0-ae95-197e1824ae89)
> 

you cant use ping directly, you must use other vpn tools in order to route the traffict, I recommend you read another issue discussion about this. 
Sorry I'm not write in the readme md
